# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Siwei Wang
title: Master student of Computer science
email: wsw765012395@gmail.co.uk
website: sc16s2w.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  sc16s2w
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
#facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: Siwei Wang
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

#Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Siwei and I'm a Master student of Computer Science. Now, I am doing thesis project related natural language processing, and this project is in  In collaboration with KB, 
  the National Library of The Netherlands. I also have experience making software and web apps. Now, I am actively searching for the job of software engineer.
  I am most skilled in: <mark>Java backend developing</mark> and <mark>Python</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Context-Aware Movie Recommendation System
        link: https://gitlab.ewi.tudelft.nl/cs4065/2020-2021/team10
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         This project adjusts its recommendations based on user feedback and gives robust, accurate recommendations based on the neural network. 
         - Design and implement a web page via Python Flask. 
         - Build a convolutional neural network model with user embedding, movie embedding, and reviewembedding. 
         - Design a graph neural network to extract representations of movies and users to do feature enrichment.
         
      - layout: top-middle
        title: Offensive Language Detection
        link: https://github.com/sc16s2w/nlp_SemEval
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         This project aims to tackle the OffensEval 2019 challenge, and there are three subtasks, including offensive language identification, categorization of offense types, and offense target identification. 
         - Fine-tune a BERT based classifier on task A and task C achieved an F1 macro score of 0.8155 for task A and 0.6456 for task C both of which rank 2nd in the competition 
         - Build an RNN model with Glove on taskB, gained an F1 macro score 0.7228(rank 3rd in the competition) 
         - Solve the problem of data imbalance by threshold adjusting and oversampling.
      - layout: top-middle
        title: Reproducibility Project
        link: https://github.com/sc16s2w/WAMDA
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         Reproduce a paper named WAMDA: Weighted Alignment of Sources for Multi-source Domain Adaptation without using pre-existing code. The paper presents a novel method for Multi-source Domain Adaptation which uses multiple sources to train a predictor based on their internal relevance and their relevance score related to the target.
      - layout: top-middle
        title: Electronic business platform
        link:  https://github.com/sc16s2w/E-shopapplication
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         The project is a full-category e-commerce shopping website (B2C). Users can search for products online, add to the shopping cart, place an order, and kill in seconds, while the administrator can manage the promotion activities of products on and off the shelves, and monitor the sales of products, make refunds. 
         - The back-end mainly uses SpringMVC, SpringBoot, SpringCloud, JWT, Nginx, FastDFS, Redis, MySql, RabbitMQ, Elasticsearch, and the front-end uses basic html, css, Javascript and NPM, Vue.js, etc.
         - UsingRabbitMQtorealizereliablemessageservice,andsolvetheproblemofinter-servicecommunicationanddistributedtrans- action problem.
         - Implementing offline client shopping cart based on LocalStorage to reduce serverpressure.
         - Realizing the intelligent filtering and search of commodities by elasticsearch.
         - Realizing the request load balancing and request current limit by nginx.

      - layout: top-middle
        title: Social platform
        link: https://github.com/sc16s2w/SocialPlatform
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         It is a social platform for all practitioners in the financial industry. It has eight main channels: News, QA, Event Organization, Dating Platform, Recruitment Information, User Center, Search Center and Third-Party Login
         - It mainly involves SpringBoot, SpringCloud, MyBatis-plus, Redis, MongoDB, ElasticSearch, Ribbon, Hystric, zuul, JWT, etc. 
         - Using RabbitMQ to store new message reminders,reduce data base access pressure
         - In order to solve the storage and query of massive data of first, second and third level comments in Tucao Tiandi, MongoDB is used for storage, which improves storage efficiency and query performance.
         - Uses Redis to cache hotspot query data, which improves system query performance
         
      - layout: top-middle
        title: Context-Aware Movie Recommendation System
        link: https://gitlab.ewi.tudelft.nl/cs4065/2020-2021/team10
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         This project adjusts its recommendations based on user feedback and gives robust, accurate recommendations based on the neural network. 
         - Design and implement a web page via Python Flask. 
         - Build a convolutional neural network model with user embedding, movie embedding, and reviewembedding. ｜
         - Design a graph neural network to extract representations of movies and users to do feature enrichment.
         
      - layout: top-middle
        title: Context-Aware Movie Recommendation System
        link: https://gitlab.ewi.tudelft.nl/cs4065/2020-2021/team10
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         This project adjusts its recommendations based on user feedback and gives robust, accurate recommendations based on the neural network. 
         - Design and implement a web page via Python Flask. 
         - Build a convolutional neural network model with user embedding, movie embedding, and reviewembedding. ｜
         - Design a graph neural network to extract representations of movies and users to do feature enrichment.
        - layout: top-middle
        title: Context-Aware Movie Recommendation System
        link: https://gitlab.ewi.tudelft.nl/cs4065/2020-2021/team10
        # link_text: Project Website
#         additional_links:
#           - title:  sproogen/modern-resume-theme
#             icon: fab fa-github
#             url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
#         quote: >
#           This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
         This project adjusts its recommendations based on user feedback and gives robust, accurate recommendations based on the neural network. 
         - Design and implement a web page via Python Flask. 
         - Build a convolutional neural network model with user embedding, movie embedding, and reviewembedding. ｜
         - Design a graph neural network to extract representations of movies and users to do feature enrichment.
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: The Boring Company
        link: boringcompany.com
        # link_text: boringcompany.com
        sub_title: Senior Network System Administrator
        caption: November 2017 - Present
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Harvard University
        caption: 2010 - 2013
        sub_title: BSc Computer Science
        quote: >
          Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Rock climbing
      - Gaming
      - Knitting
      - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

      Look at this cool image  
      ![Trees](/modern-resume-theme/images/landscape-trees.jpg "Trees")

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
